title: Taylor Smith
baseurl: ""
url: "https://www.tsmithcreative.com"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - node_modules # Apparently this is magic sauce to make Jekyll less super slow
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - README.md
keep_files:
  - css   # Don't clobber site CSS, this way I don't have to store compiled CSS
  - js    # Don't clobber site JS, which is built with Gulp and includes Photoswipe
  - gfx   # Don't clobber site graphics/images/assets
  - assets # Don't clobber page/post assets; they're minimized with Gulp now
  - .htaccess
  - favicon.ico
  - favicon-16x16.png
  - favicon-32x32.png

# Site settings
permalink: /blog/:year/:slug/

defaults:
  - scope:
      type: projects
    values:
      layout: project
      photoswipe: true
  - scope:
      type: posts
    values:
      commenting: true

collections:
  projects:
    output: true
    permalink: /project/:slug/
