title: Taylor Smith
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.tsmithcreative.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tsmith512
github_username:  tsmith512

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - node_modules # Apparently this is magic sauce to make Jekyll less super slow
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - README.md
keep_files:
  - css   # Don't clobber site CSS, this way I don't have to store compiled CSS
  - js    # Don't clobber site JS, which is built with Gulp and includes Photoswipe
  - gfx   # Don't clobber site graphics/images/assets
  - .htaccess

# Site settings
permalink: /blog/:year/:slug/

defaults:
  - scope:
      type: projects
    values:
      layout: project
      photoswipe: true

collections:
  projects:
    output: true
    permalink: /project/:slug/
